### ISSUE TITLE
Do you use stylegan to generate voice?

### ISSUE THREAD

**Issue by c1a1o1** [M0NWY/Spectools#1]
Do you use stylegan to generate voice?

**Comment by M0NWY** [comment]
Alas, no. It turns out that I had made a major oversight when thinking up
how to use styleGAN. The model architecture is tuned to be image specific
even before training. The major issues i had were to do with the phase data
( blue channel). The model didn’t even start to put details in the blue
channel and it looks almost random for the inputs. I’ve abandoned it now
that jukebox has been released and this can definitely do voice ( well..
singing!)
I’d look into that.

Cheers.

**Comment by c1a1o1** [comment]
OK! Thanks for your answer!
